name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MV_AZURE }}
          username: Joseadmin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Clean start
            rm -rf ~/integraciones-tagamics
            mkdir -p ~/integraciones-tagamics
            cd ~/integraciones-tagamics
            
            # Simple clone
            git clone https://github.com/TestIAMCH/integraciones-tagamics.git .

            # Docker commands (No sudo)
            docker stop tagamics-app || true
            docker rm tagamics-app || true
            docker build -t tagamics-app .
            docker run -d --name tagamics-app -p 8080:80 --restart always tagamics-app
